### ISSUE TITLE
handle termination of init script gracefully

### ISSUE THREAD

**Issue by Hotell** [Hotell/typescript-lib-starter#153]
### Use case(s)

Currently when used runs `yarn` after clone and terminates prompts, "initialization" process will run anyways with destructive consequences ( removed files... re-initialised git etc).

All that needs to be done is to handle CTRL+C gracefully -> just terminate without executing the script logic

**Comment by langpavel** [comment]
There is onCancel hook in prompts. Just call process.exit there
